---
title: "Commute Times"
output: html-notebook
---

```{r, message=FALSE}
# load libraries
library(ggplot2)
library(dplyr)
library(rdd)
```

# Task 1
```{r}
# load file as dataframe
snow_df <- read.csv("snow.csv")
```

# Task 2
```{r}
# inspect dataframe
head(snow_df)
```

# Task 3
```{r}
# create base plot
scatter_base <- ggplot(
  data = snow_df,
  aes(
    # forcing variable
    x = snowfall,
    # outcome variable
    y = minutes,
    color = emergency,
    shape = emergency
  )
) + 
# add points
geom_point()

# print plot
scatter_base
```

# Task 4
```{r}
# update base plot with line at cutpoint
scatter_cutpoint <-
  scatter_base + 
  geom_vline(
    xintercept = 4,
    linetype = 'dashed'
  )

# print plot
scatter_cutpoint
```

# Task 5
```{r, message = FALSE}
# add linear best fit lines for each group
scatter_fit <- scatter_cutpoint +
  geom_smooth(aes(group=emergency), method = "lm")

# print plot
scatter_fit 
```

# Task 6
```{r, message=FALSE}
# calculate bandwidth
snow_ik_bw <- IKbandwidth(
  # forcing variable
  X = snow_df$snowfall,
  # outcome variable
  Y = snow_df$minutes,
  cutpoint = 4
)

# print bandwidth
snow_ik_bw
```

# Task 7
```{r}
# add bandwidth lines to plot
scatter_bw <- 
# previous plot
scatter_cutpoint + 
  # add solid lines, lines one BW above or below cutpoint 
  # (of 4)
  geom_vline(
    xintercept = 4 + c(-snow_ik_bw, snow_ik_bw))

# print plot
scatter_bw

```

# Task 8
```{r, message=FALSE}
# fit local linear regression model
snow_rdd <- RDestimate(
  #outcome model
  formula = minutes ~ snowfall,
  cutpoint = 4,
  bw = snow_ik_bw, 
  data = snow_df
)
```

# Task 9
```{r}
# results of local linear regression model
snow_rdd
```

# Task 10
```{r}
# print the number of observations
snow_rdd$obs
```

# Task 11
```{r}
# print the standard errors
snow_rdd$se
```